### ISSUE TITLE
请求引用

### ISSUE THREAD

**Issue by drinktoomuchsax** [Ethylene9160/EE340_Statictical_Learning_for_Data_Science#1]
hallo，就是想在[course-hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)上引用一下：）

**Comment by Ethylene9160** [comment]
啊 这学期才选了这门课，仓库里还没放东西emmmm

**Comment by drinktoomuchsax** [comment]
加油，带着学弟学妹的期待完成这个仓库 :muscle:

**Comment by Ethylene9160** [comment]
笑兮了，待鼠鼠这学期上完就能给了哈哈哈哈哈哈

**Comment by Ethylene9160** [comment]
应该算是完了emmm

**Comment by drinktoomuchsax** [comment]
respect！

**Comment by drinktoomuchsax** [comment]
你好，再次感谢你创建这个仓库！

已经提交了[更新](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero/pull/14)。根据仓库内容的主要分类——项目和课件，我将其分为了两个部分：Project 和 Lecture。

非常感谢你的工作，也欢迎未来相关课程提交pr : )
